CREATE TABLE Brokers(
	BrokerID INT IDENTITY(1,1) PRIMARY KEY,
	BrokerName VARCHAR(100) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	Exchange VARCHAR(50) NOT NULL,
	CreatedDate DATE DEFAULT GETDATE() 

)