CREATE TABLE Securities(
	SecurityID INT IDENTITY(1,1) PRIMARY KEY,
	Ticker VARCHAR(10) NOT NULL,
	SecurityName VARCHAR(100) NOT NULL,
	AssetType VARCHAR(30) NOT NULL,
	Currency VARCHAR(10) NOT NULL,
	Exchange VARCHAR(50) NOT NULL,
	CreatedDate DATE DEFAULT GETDATE(),

)